import type { FinanceSnapshot } from "./types";

function daysAgo(days: number, hour = 9): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

/**
 * Local sample data used to build out the UI. This mirrors the shape returned by
 * the Convex `finance.getSnapshot` query so it can be swapped in later with no
 * changes to the screens.
 */
export const mockSnapshot: FinanceSnapshot = {
  accounts: [
    {
      balance: 482_355,
      color: "#2F6BFF",
      currency: "GHS",
      id: "acc_checking",
      institution: "Chase",
      name: "Everyday",
      symbol: "creditcard.fill",
      type: "current",
    },
    {
      balance: 1_864_200,
      color: "#16A34A",
      currency: "GHS",
      id: "acc_savings",
      institution: "Ally",
      name: "Rainy Day",
      symbol: "banknote.fill",
      type: "savings",
    },
    {
      balance: 3_421_780,
      color: "#9333EA",
      currency: "GHS",
      id: "acc_invest",
      institution: "Fidelity",
      name: "Brokerage",
      symbol: "chart.line.uptrend.xyaxis",
      type: "investment",
    },
    {
      balance: -128_940,
      color: "#DC2626",
      currency: "GHS",
      id: "acc_credit",
      institution: "Chase",
      name: "Sapphire",
      symbol: "creditcard.circle.fill",
      type: "general",
    },
    {
      balance: 24_000,
      color: "#F59E0B",
      currency: "GHS",
      id: "acc_cash",
      institution: "Cash",
      name: "Wallet",
      symbol: "dollarsign.circle.fill",
      type: "cash",
    },
  ],
  budgets: [
    {
      category: "Groceries",
      color: "#16A34A",
      currency: "GHS",
      id: "bud_groceries",
      limit: 60_000,
      name: "Groceries",
      notifyAtThreshold: true,
      notifyOnOverspend: true,
      period: "monthly",
      spent: 42_300,
      symbol: "cart.fill",
      tagId: null,
      tagIds: [],
      tags: [],
    },
    {
      category: "Eating Out",
      color: "#F59E0B",
      currency: "GHS",
      id: "bud_dining",
      limit: 35_000,
      name: "Dining out",
      notifyAtThreshold: true,
      notifyOnOverspend: true,
      period: "monthly",
      spent: 31_800,
      symbol: "fork.knife",
      tagId: null,
      tagIds: [],
      tags: [],
    },
    {
      category: "Transportation",
      color: "#2563EB",
      currency: "GHS",
      id: "bud_transport",
      limit: 25_000,
      name: "Transport",
      notifyAtThreshold: true,
      notifyOnOverspend: false,
      period: "monthly",
      spent: 9_400,
      symbol: "car.fill",
      tagId: null,
      tagIds: [],
      tags: [],
    },
    {
      category: "Outing",
      color: "#DC2626",
      currency: "GHS",
      id: "bud_fun",
      limit: 20_000,
      name: "Entertainment",
      notifyAtThreshold: true,
      notifyOnOverspend: true,
      period: "monthly",
      spent: 22_100,
      symbol: "gamecontroller.fill",
      tagId: null,
      tagIds: [],
      tags: [],
    },
  ],
  monthlyTotals: [{ currency: "GHS", totalIn: 450_000, totalOut: 108_432 }],
  plannedPaymentsOverdueCount: 0,
  transactions: [
    {
      accountId: "acc_credit",
      accountName: "Sapphire",
      amount: -8_432,
      category: "Groceries",
      color: "#16A34A",
      createdByName: "",
      currency: "GHS",
      date: daysAgo(0, 18),
      id: "txn_1",
      merchant: "Whole Foods",
      symbol: "cart.fill",
      tags: [{ id: "tag_groceries", name: "Essentials", color: "#16A34A" }],
      transactionKind: "expense",
    },
    {
      accountId: "acc_checking",
      accountName: "Everyday",
      amount: 412_500,
      category: "Income",
      color: "#16A34A",
      createdByName: "",
      currency: "GHS",
      date: daysAgo(0, 8),
      id: "txn_2",
      merchant: "Acme Payroll",
      symbol: "arrow.down.circle.fill",
      tags: [],
      transactionKind: "income",
    },
    {
      accountId: "acc_credit",
      accountName: "Sapphire",
      amount: -1_870,
      category: "Transport",
      color: "#2563EB",
      createdByName: "",
      currency: "GHS",
      date: daysAgo(1, 21),
      id: "txn_3",
      merchant: "Uber",
      symbol: "car.fill",
      tags: [{ id: "tag_commute", name: "Commute", color: "#2563EB" }],
    },
    {
      accountId: "acc_credit",
      accountName: "Sapphire",
      amount: -1_599,
      category: "Subscriptions",
      color: "#DC2626",
      createdByName: "",
      currency: "GHS",
      date: daysAgo(2, 6),
      id: "txn_4",
      merchant: "Netflix",
      symbol: "play.tv.fill",
      tags: [],
    },
    {
      accountId: "acc_checking",
      accountName: "Everyday",
      amount: -640,
      category: "Coffee",
      color: "#B45309",
      createdByName: "",
      currency: "GHS",
      date: daysAgo(3, 10),
      id: "txn_5",
      merchant: "Blue Bottle",
      symbol: "cup.and.saucer.fill",
      tags: [{ id: "tag_treats", name: "Treats", color: "#F59E0B" }],
    },
    {
      accountId: "acc_checking",
      accountName: "Everyday",
      amount: -50_000,
      category: "Transfer",
      color: "#6366F1",
      createdByName: "",
      currency: "GHS",
      date: daysAgo(4, 12),
      fromAccountId: "acc_checking",
      fromAccountName: "Everyday",
      id: "txn_6",
      merchant: "Transfer to Savings",
      symbol: "arrow.left.arrow.right",
      tags: [],
      toAccountId: "acc_savings",
      toAccountName: "Rainy Day",
      transactionKind: "transfer_out",
    },
  ],
};
