// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

import "uniwind";

declare module "uniwind" {
  export interface UniwindConfig {
    themes: readonly ["light", "dark"];
  }
}
